package sf.modelo;
// Generated 13/09/2016 11:20:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Despesa generated by hbm2java
 */
public class Despesa  implements java.io.Serializable {


     private Integer desCod;
     private Categoria categoria;
     private String desDesc;
     private Boolean desPago;
     private int desNrodeParcelas;
     private boolean desFixo;
     private Set parcelas = new HashSet(0);

    public Despesa() {
    }

	
    public Despesa(Categoria categoria, int desNrodeParcelas, boolean desFixo) {
        this.categoria = categoria;
        this.desNrodeParcelas = desNrodeParcelas;
        this.desFixo = desFixo;
    }
    public Despesa(Categoria categoria, String desDesc, Boolean desPago, int desNrodeParcelas, boolean desFixo, Set parcelas) {
       this.categoria = categoria;
       this.desDesc = desDesc;
       this.desPago = desPago;
       this.desNrodeParcelas = desNrodeParcelas;
       this.desFixo = desFixo;
       this.parcelas = parcelas;
    }
   
    public Integer getDesCod() {
        return this.desCod;
    }
    
    public void setDesCod(Integer desCod) {
        this.desCod = desCod;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getDesDesc() {
        return this.desDesc;
    }
    
    public void setDesDesc(String desDesc) {
        this.desDesc = desDesc;
    }
    public Boolean getDesPago() {
        return this.desPago;
    }
    
    public void setDesPago(Boolean desPago) {
        this.desPago = desPago;
    }
    public int getDesNrodeParcelas() {
        return this.desNrodeParcelas;
    }
    
    public void setDesNrodeParcelas(int desNrodeParcelas) {
        this.desNrodeParcelas = desNrodeParcelas;
    }
    public boolean isDesFixo() {
        return this.desFixo;
    }
    
    public void setDesFixo(boolean desFixo) {
        this.desFixo = desFixo;
    }
    public Set getParcelas() {
        return this.parcelas;
    }
    
    public void setParcelas(Set parcelas) {
        this.parcelas = parcelas;
    }




}


