package sf.modelo;
// Generated 13/09/2016 11:20:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Meta generated by hbm2java
 */
public class Meta  implements java.io.Serializable {


     private Integer metCod;
     private Double metValor;
     private String metDescricao;
     private String metNome;
     private Date metData;

    public Meta() {
    }

    public Meta(Double metValor, String metDescricao, String metNome, Date metData) {
       this.metValor = metValor;
       this.metDescricao = metDescricao;
       this.metNome = metNome;
       this.metData = metData;
    }
   
    public Integer getMetCod() {
        return this.metCod;
    }
    
    public void setMetCod(Integer metCod) {
        this.metCod = metCod;
    }
    public Double getMetValor() {
        return this.metValor;
    }
    
    public void setMetValor(Double metValor) {
        this.metValor = metValor;
    }
    public String getMetDescricao() {
        return this.metDescricao;
    }
    
    public void setMetDescricao(String metDescricao) {
        this.metDescricao = metDescricao;
    }
    public String getMetNome() {
        return this.metNome;
    }
    
    public void setMetNome(String metNome) {
        this.metNome = metNome;
    }
    public Date getMetData() {
        return this.metData;
    }
    
    public void setMetData(Date metData) {
        this.metData = metData;
    }




}


