package sf.modelo;
// Generated 13/09/2016 11:20:51 by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private String logUsuario;
     private String logSenha;

    public Login() {
    }

	
    public Login(String logUsuario) {
        this.logUsuario = logUsuario;
    }
    public Login(String logUsuario, String logSenha) {
       this.logUsuario = logUsuario;
       this.logSenha = logSenha;
    }
   
    public String getLogUsuario() {
        return this.logUsuario;
    }
    
    public void setLogUsuario(String logUsuario) {
        this.logUsuario = logUsuario;
    }
    public String getLogSenha() {
        return this.logSenha;
    }
    
    public void setLogSenha(String logSenha) {
        this.logSenha = logSenha;
    }




}


