package sf.modelo;
// Generated 13/09/2016 11:20:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Receita generated by hbm2java
 */
public class Receita  implements java.io.Serializable {


     private Integer recCod;
     private Categoria categoria;
     private String recDesc;
     private Boolean recPago;
     private int recNrodeParcelas;
     private boolean recFixo;
     private Set parcelas = new HashSet(0);

    public Receita() {
    }

	
    public Receita(Categoria categoria, int recNrodeParcelas, boolean recFixo) {
        this.categoria = categoria;
        this.recNrodeParcelas = recNrodeParcelas;
        this.recFixo = recFixo;
    }
    public Receita(Categoria categoria, String recDesc, Boolean recPago, int recNrodeParcelas, boolean recFixo, Set parcelas) {
       this.categoria = categoria;
       this.recDesc = recDesc;
       this.recPago = recPago;
       this.recNrodeParcelas = recNrodeParcelas;
       this.recFixo = recFixo;
       this.parcelas = parcelas;
    }
   
    public Integer getRecCod() {
        return this.recCod;
    }
    
    public void setRecCod(Integer recCod) {
        this.recCod = recCod;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getRecDesc() {
        return this.recDesc;
    }
    
    public void setRecDesc(String recDesc) {
        this.recDesc = recDesc;
    }
    public Boolean getRecPago() {
        return this.recPago;
    }
    
    public void setRecPago(Boolean recPago) {
        this.recPago = recPago;
    }
    public int getRecNrodeParcelas() {
        return this.recNrodeParcelas;
    }
    
    public void setRecNrodeParcelas(int recNrodeParcelas) {
        this.recNrodeParcelas = recNrodeParcelas;
    }
    public boolean isRecFixo() {
        return this.recFixo;
    }
    
    public void setRecFixo(boolean recFixo) {
        this.recFixo = recFixo;
    }
    public Set getParcelas() {
        return this.parcelas;
    }
    
    public void setParcelas(Set parcelas) {
        this.parcelas = parcelas;
    }




}


