/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sf.visao;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import sf.controle.GerenciarCategoriaCONTROLE;
import sf.modelo.CategoriaBEAN;

/**
 *
 * @author Administrador
 */
public class GerenciarCategoriaGUI extends javax.swing.JFrame {

    /**
     * Creates new form GerenciarCategoriaGUI
     */
    GerenciarCategoriaCONTROLE gcc = new GerenciarCategoriaCONTROLE();
    JComboBox jsub;
    private String nomeAntigo = "";
    private int categoriaIndex;
    private String descAntigo = "";

    public GerenciarCategoriaGUI() {
        initComponents();
        meuInit();
    }

    public void meuInit() {

        //  panelCat.setVisible(false);
        setCategoria();
        preencheTable();

    }

    public void preencheTable() {
        ArrayList<CategoriaBEAN> cb = new ArrayList();
        gcc.pegaCat(cb);
        String[] colunas = new String[]{"Categoria", "Descrição"};
        DefaultTableModel model = new DefaultTableModel(null, colunas);

        for (CategoriaBEAN c : cb) {

            String[] nomecat = new String[]{c.getCatNome(), c.getCatDescricao()};

            model.addRow(nomecat);

        }
        jTableCat.setModel(model);

        // TableColumn colunasubcategoria = jTableCat.getColumnModel().getColumn(1);
        // //necessitareparo
        // colunasubcategoria.setCellEditor(new MyComboBoxEditor(cb));
        //String [] teste={"A", "B", "C"};
        //colunasubcategoria.setCellRenderer(new MyComboBoxRenderer(teste));
        //    colunasubcategoria.setCellRenderer();
    }

    public void tableSelectionTratamento() {

        int[] localselecionado = {jTableCat.getSelectedRow(), jTableCat.getSelectedColumn()};

        if (localselecionado[1] == 0) {

            categoriaIndex = jTableCat.getSelectedRow();
            String nomeatual = String.valueOf(jTableCat.getModel().getValueAt(localselecionado[0], localselecionado[1]));
            jtNome.setText(nomeatual);
            nomeAntigo = nomeatual;
            gcc.getCatCodigo(localselecionado[0]);
        }
    }

    public void setCategoria() {
        // jComboCat.removeAllItems();
        ArrayList<CategoriaBEAN> cb = new ArrayList();
        gcc.pegaCat(cb);
        //for (CategoriaBEAN c : cb) {
        //  jComboCat.addItem(c.getCatNome());

        //}
    }

    public void botaoInserir() {
        if (!jtNome.getText().equals(" ")) {
            String catNome = jtNome.getText();
            String catDesc = " ";
            if (!jtaDesc.getText().equals(" ")) {
                catDesc = jtaDesc.getText();
            }

            //  if (jRadioSub.isSelected()) {
            //    gcc.getCatCodigo(jComboCat.getSelectedIndex());
            //} else {
            gcc.inserirCategoria(catNome, catDesc);
            //}

        }
        setCategoria();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDesc = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCat = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btInserir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Categorias");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Digite o nome da categoria:");

        jtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Dê uma descrição para essa categoria:");

        jtaDesc.setColumns(20);
        jtaDesc.setRows(5);
        jScrollPane1.setViewportView(jtaDesc);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addComponent(jtNome))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Suas categorias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N

        jTableCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Categoria", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCatMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableCat);
        if (jTableCat.getColumnModel().getColumnCount() > 0) {
            jTableCat.getColumnModel().getColumn(0).setResizable(false);
            jTableCat.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Inserir.png"))); // NOI18N
        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Deletar.png"))); // NOI18N
        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Atualizar.png"))); // NOI18N
        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Cancelar.png"))); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jButton3)
                .addGap(76, 76, 76)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInserir)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNomeActionPerformed

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        // TODO add your handling code here:
        //Pega os dados dos textFields e passa passa para o CONTROLE para ele aficionar
        try {
            botaoInserir();
            preencheTable();
        } catch (Exception ex) {

            Logger.getLogger(GerenciarCategoriaGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btInserirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<CategoriaBEAN> cb = gcc.pegaCat();
        gcc = new GerenciarCategoriaCONTROLE();
        int confirma = JOptionPane.showConfirmDialog(null, "Voce tem certeza que quer deletar essa categoria (Ela irá deletar todos as suas contas que estão refeciadas a ela)?", "Deleção", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            for (int i = 0; i <= gcc.deletaD().getDespesa().size(); i++) {
                System.out.println("Chego");
                System.out.println(categoriaIndex);
                if (gcc.deletaD().getDespesa().isEmpty() && gcc.deletaD().getReceita().isEmpty()) {
                    gcc.deletaCategoria(categoriaIndex);
                    System.out.println("Chego 4");
                    //     gcc.verificaDeletado().deletaDespesa(categoriaIndex);
                    System.out.println("Chego 5");
                    DefaultTableModel model = (DefaultTableModel) jTableCat.getModel();
                    //          CategoriaBEAN cat = new CategoriaBEAN();
                    //        cat.setCatNome(jtNome.getText());
                    //     gcc.deletaCategoria(buscaCodUsandoNome());
                    model.removeRow(jTableCat.getSelectedRow());
                } else if (gcc.deletaD().getDespesa().size() > 1 && gcc.deletaD().getReceita().size() > 1 && gcc.deletaD().getDespesa().get(i).getDes_catCod() != cb.get(categoriaIndex).getCatCod() || gcc.deletaD().getReceita().get(i).getRec_catCod() != cb.get(categoriaIndex).getCatCod()) {
                    gcc.deletaCategoria(categoriaIndex);
                    System.out.println("Chego 4");
                    //     gcc.verificaDeletado().deletaDespesa(categoriaIndex);
                    System.out.println("Chego 5");
                    DefaultTableModel model = (DefaultTableModel) jTableCat.getModel();
                    //          CategoriaBEAN cat = new CategoriaBEAN();
                    //        cat.setCatNome(jtNome.getText());
                    //     gcc.deletaCategoria(buscaCodUsandoNome());
                    model.removeRow(jTableCat.getSelectedRow());
                } else if (gcc.deletaD().getDespesa().get(i).getDes_catCod() == cb.get(categoriaIndex).getCatCod() || gcc.deletaD().getReceita().get(i).getRec_catCod() == cb.get(categoriaIndex).getCatCod()) {
                    System.out.println("Chego 1");
                    gcc.deletaP().deletaParcelaDespesa(gcc.deletaD().getDespesa().get(i).getDesCod());
                    gcc.deletaP().deletaParcelaReceita(gcc.deletaD().getReceita().get(i).getRecCod());
                    System.out.println("Chego 2");
                    gcc.deletaD().deletaDespesa(gcc.deletaD().getDespesa().get(i).getDesCod());
                    System.out.println("Cat Index " + categoriaIndex);
                    System.out.println("Chego 3");

                    System.out.println("Chego 6");
                    gcc.deletaD().deletaReceita(gcc.deletaD().getReceita().get(i).getRecCod());
                    System.out.println("Chego 7");

                    gcc.deletaCategoria(categoriaIndex);
                    System.out.println("Chego 4");
                    //     gcc.verificaDeletado().deletaDespesa(categoriaIndex);
                    System.out.println("Chego 5");
                    DefaultTableModel model = (DefaultTableModel) jTableCat.getModel();
                    //          CategoriaBEAN cat = new CategoriaBEAN();
                    //        cat.setCatNome(jtNome.getText());
                    //     gcc.deletaCategoria(buscaCodUsandoNome());
                    model.removeRow(jTableCat.getSelectedRow());
                }
            }
        } else {

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private int buscaCodUsandoNome() {

        ArrayList<CategoriaBEAN> cb = gcc.pegaCat();
        int codigo = 0;

        for (CategoriaBEAN categoriaBEAN : cb) {
            if (categoriaBEAN.getCatNome().equals(nomeAntigo) == true) {
                codigo = categoriaBEAN.getCatCod();

                break;
            }
        }
        System.out.println("codigo: " + codigo);
        return codigo;
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        gcc = new GerenciarCategoriaCONTROLE();
        String nome = jtNome.getText();
        int codigo = buscaCodUsandoNome();
        CategoriaBEAN categoria = new CategoriaBEAN();
        categoria.setCatCod(codigo);
        categoria.setCatNome(nome);
        categoria.setCatDescricao(jtaDesc.getText());
        System.out.println("codigo categoria " + codigo + nome);
        gcc.atualizaCategoria(categoria);
        DefaultTableModel model = (DefaultTableModel) jTableCat.getModel();
        model.setValueAt(nome, jTableCat.getSelectedRow(), jTableCat.getSelectedColumn());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTableCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCatMouseClicked
        // TODO add your handling code here:
        tableSelectionTratamento();
    }//GEN-LAST:event_jTableCatMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarCategoriaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarCategoriaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarCategoriaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarCategoriaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarCategoriaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInserir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableCat;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextArea jtaDesc;
    // End of variables declaration//GEN-END:variables
}
